    version: "3"
    services:
      client:
        image: "asheer/client-app"
        mem_limit: 128m
        hostname: client
      server:
        image: "asheer/server-app"
        mem_limit: 128m
        hostname: api
        secrets: |
            "REDIS_HOST=${{ secrets.REDIS_HOST }}"
            "REDIS_PORT=6379"
            "PGUSER=${{ secrets.PGUSER }}"
            "PGHOST=${{ secrets.PGHOST }}"
            "PGDATABASE=${{ secrets.PGDATABASE }}"
            "PGPASSWORD=${{ secrets.PGPASSWORD }}"
            "PGPORT=5379"
      worker:
        image: "asheer/worker-app"
        mem_limit: 128m
        hostname: worker
        environment:
          - REDIS_HOST=$REDIS_HOST
          - REDIS_PORT=$REDIS_PORT
      nginx:
        image: "asheer/nginx-app"
        mem_limit: 128m
        hostname: nginx
        ports:
          - "80:80"


