name: "PR build and test"
run-name: "Build and test job"
on:
  push:
    branches-ignore:
      - main

jobs:
  checkpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build ./client --file ./client/Dockerfile.dev --tag asheer/client-app:latest
      - run: docker run -e CI=true  asheer/client-app:latest npm run test -- --coverage