name: "PR build and test"

on: [push]

jobs:
  checkpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build ../client --file ../client/Dockerfile.dev --tag asheer/client-app:latest
      - run: docker run -e CI=true  asheer/client-app:latest npm run test -- --coverage