name:  "Release new Image"
run-name: Releasing prod version
on:
  push:
    branches: [main]

jobs:
    releaseimage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker build ./client --tag asheer/client-app:latest


