name:  "Release new Image"
run-name: Releasing prod version
on:
  pull_request:
    types:
        - closed
    branches: [main]

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build ./client --tag asheer/client-app:latest
      - run: docker build ./worker --tag asheer/worker-app:latest
      - run: docker build ./nginx --tag asheer/nginx-rp:latest
      - run: docker build ./server --tag asheer/server-app:latest
    
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Docker Push client
        run: docker push ${{secrets.DOCKER_USERNAME}}/client-app
      - name: Docker Push workerapp
        run: docker push ${{secrets.DOCKER_USERNAME}}/worker-app
      - name: Docker Push nginx-rp
        run: docker push ${{secrets.DOCKER_USERNAME}}/nginx-rp
      - name: Docker Push server-app
        run: docker push ${{secrets.DOCKER_USERNAME}}/server-app

      - name: Deploy 2 EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fiboapp
          environment_name: Fiboapp-env
          existing_bucket_name: ${{ secrets.ASS3_BUCKET }}
          region: us-west-2
          version_label: ${{ github.sha }}
          use_existing_version_if_available: true
          deployment_package: deploy.zip