name:  "Release new Image"
run-name: Releasing prod version
on:
  pull_request:
    types:
        - closed
    branches: [main]

jobs:
  if_merged:
    if:  github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build ./client --tag asheer/client-app:latest
      - run: docker build ./worker --tag asheer/worker-app:latest
      - run: docker build ./nginx --tag asheer/nginx-rp:latest
      - run: docker build ./server --tag asheer/server-app:latest
      